apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aisaas-broker.fullname" . }}-catalog
  labels: {{- include "aisaas-broker.labels" . | nindent 4 }}
data:
  catalog.json: | 
    {
        "services": [{
            "id": "{{ default uuidv4 .Values.config.serviceId }}",
            "name": "{{ printf "%s-api-%s-%s" .Release.Name .Release.Namespace .Values.global.shootName }}",
            "description": "{{  include "template-value" ( dict "value" .Values.config.displayName "context" . ) }}",
            "bindable": true,
            "plans": [
                {{- range $i, $plans := .Values.config.plans }}
                {{- if $i -}},{{- end -}}
                {
                    "name": "{{ $plans.name }}",
                    "description": "{{ $plans.description }}",
                    "id": "{{ default uuidv4 $plans.planId }}"
                }
                {{- end }}
            ]
        }]
    }