global:
  imagePullSecret: {}
  domain: a1b2c3.kyma.ondemand.com
  shootName: a1b2c3 

router:
  image:  
    repository: sap-demo/ai-router
    tag: latest

srv:
  image:
    repository: sap-demo/ai-srv
    tag: latest

hana_deployer:
  image:
    repository: sap-demo/ai-db
    tag: latest

html5_apps_deployer:
  image:
    repository: sap-demo/ai-html5-deployer
    tag: latest

xsuaa:
  parameters:
   oauth2-configuration:
    redirect-uris:
      - https://*.a1b2c3.kyma.ondemand.com/**
      - http://*.localhost:5000/**
      - http://localhost:5000/**