{{ if .Values.expose.enabled}}
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ include "ai-router.fullname" . }}
  labels: {{- include "ai-router.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.global.gateway | default "kyma-system/kyma-gateway" }}
  host: {{ printf "%s.%s" ( include "ai-router.exposeHost" . ) $.Values.global.domain }}
  rules:
  - methods:
      - GET
      - POST
      - PUT
      - DELETE
      - HEAD
    path: /.*
    accessStrategies:
      - handler: allow
  service:
    name: {{ include "ai-router.fullname" . }}
    port: {{ .Values.port }}
{{ end }}

