apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "ai-router.labels" . | nindent 4 }}
  name: {{ include "ai-router.fullname" . }}
spec:
  selector:
    matchLabels: {{- include "ai-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "ai-router.selectorLabels" . | nindent 8 }}
    spec:
      {{- if (include "ai-router.imagePullSecretName" .) }}
      imagePullSecrets:
        - name: {{ include "ai-router.imagePullSecretName" . }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken | default false }}
      serviceAccountName: {{ .Values.serviceAccount.enabled  | ternary ( include "ai-router.fullname" . ) "default" }}
      containers:
      - image: {{ include "ai-router.imageName" . }}
        name: {{ include "ai-router.name" . }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        {{- if .Values.envSecretNames }}
        envFrom:
        {{- range $secretName := .Values.envSecretNames }}
        - secretRef:
            name: {{ $secretName }}
        {{- end }}
        {{- end }}
        env:
        {{- if .Values.bindings }}
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        {{- end }}
        - name: PORT
          value: {{ .Values.port | quote }}
        - name: TMPDIR
          value: /tmp
        {{- $envVars := (include "ai-router.processEnv" .Values.env | fromJson) }}
        {{- if not (eq (len $envVars.vars) 0) }}
        {{- $envVars.vars | toYaml | nindent 8}}
        {{- end }}
        {{- if not $envVars.appName}}
        - name: APPLICATION_NAME
          value: {{ include "ai-router.fullname" . }}
        {{- end }}
        {{- if not $envVars.tenantHostPattern}}
        - name: TENANT_HOST_PATTERN
          value: "^(.*)-{{ include "ai-srv.exposeHost" . }}"
        {{- end }}
        {{- if not $envVars.externalReverseProxy }}
        - name: EXTERNAL_REVERSE_PROXY 
          value: "true"
        {{- end }}
        {{- if not $envVars.appURI}}
        - name: APPLICATION_URI
          value: {{ include "ai-router.applicationUri" . }}
        {{- end }}
        {{- if .Release.Namespace }}
        - name: KYMA_NAMESPACE
          value: {{ .Release.Namespace }}
        {{- end }}
        - name: EXPOSED_HOST
          value: {{ include "ai-srv.exposeHost" . }}
        livenessProbe:
        {{- if .Values.health_check.liveness.path }}
          httpGet:
            path: {{ .Values.health_check.liveness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
        readinessProbe:
        {{- if .Values.health_check.readiness.path }}
          httpGet:
            path: {{ .Values.health_check.readiness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
        startupProbe:
        {{- if .Values.health_check.liveness.path }}
          httpGet:
            path: {{ .Values.health_check.liveness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
          failureThreshold: {{ div (add1 .Values.startupTimeout) 2 }}
          periodSeconds: 2
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- range $volume := .Values.additionalVolumes }}
        - name: {{ $volume.name | quote }}
          {{- toYaml $volume.volumeMount  | nindent 10 }}
        {{- end }}
        {{- include "ai-router.serviceMounts" . | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      {{- if .Values.ha.enabled }}
      topologySpreadConstraints:
      - labelSelector:
          matchLabels: {{- include "ai-router.selectorLabels" . | nindent 12 }}
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      {{- end }}
      volumes:
      - emptyDir: {}
        name: tmp
      {{- include "ai-router.serviceVolumes" . | nindent 6 }}
      {{- range $volume := .Values.additionalVolumes }}
      -
        {{- omit $volume "volumeMount" | toYaml  | nindent 8 }}
      {{- end }}
