apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ai-router.fullname" . }}
  labels: {{- include "ai-router.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels: {{- include "ai-router.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: istio-ingressgateway
        namespaceSelector:
          matchLabels:
            name: istio-system
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: oathkeeper
            app.kubernetes.io/instance: ory
        namespaceSelector:
          matchLabels:
            name: kyma-system