{{- if .Values.ha.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-router.fullname" . }}
  labels: {{- include "ai-router.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.ha.pdb.minAvailable | default 1 }}
  selector:
    matchLabels: {{- include "ai-router.selectorLabels" . | nindent 6 }}
{{- end }}
