apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "ai-srv.fullname" . }}
  labels: {{- include "ai-srv.labels" . | nindent 4 }}
spec:
  selector: 
    matchLabels: {{- include "ai-srv.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
      - source:
          principals: 
            - {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace ( default ( printf "%s-%s" .Release.Name "router" ) .Values.global.router.fullName ) }}
            - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account