apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-srv.fullname" . }}
  labels: {{- include "ai-srv.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector: {{- include "ai-srv.selectorLabels" . | nindent 4 }}
