{{- if not .Values.apim.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "aisaas-api.fullname" . }}
  labels: {{- include "aisaas-api.labels" . | nindent 4 }}
spec:
  selector: 
    matchLabels: {{- include "aisaas-api.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals: 
          - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
{{- end }}