apiVersion: v1
kind: Service
metadata:
  name: {{ include "aisaas-api.fullname" . }}
  labels: {{- include "aisaas-api.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector: {{- include "aisaas-api.selectorLabels" . | nindent 4 }}
