@xsuaaHostname = https://sap-demo.authentication.eu10.hana.ondemand.com
@btpXsuaaClient = sb-ai-dev-sap-demo!b12345
@btpXsuaaSecret = abcd1234abcd1234abcd1234
@btpAppHostname = https://sap-demo-dev-ai-srv.cfapps.eu10.hana.ondemand.com 


### GET XSUAA TOKEN

# @name getXsuaaToken
POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{btpXsuaaClient}}:{{btpXsuaaSecret}}

client_id={{btpXsuaaClient}}
&client_secret={{btpXsuaaSecret}}
&grant_type=client_credentials


### ADD MAILS
@token = {{getXsuaaToken.response.body.$.access_token}}

# @name addMails
POST {{btpAppHostname}}/odata/v4/mail-insights/addMails
content-type: application/json
Authorization: Bearer {{token}}

{
  "mails": [
    {
        "subject": "Potřebuji pomoc s plánováním více měst v Evropě",
        "body": "Dobrý den týmu ThorTours, plánuji více měst v Evropě na příští léto a mám problémy s nalezením nejlepšího způsobu, jak rezervovat lety a hotely. Můžete mi pomoci vytvořit itinerář, který zahrnuje Řím, Paříž, Berlín a Barcelonu?\nDěkuji předem,\nKate Willson ",
        "senderEmailAddress": "kate.willson@tttraveler.org"
    },
    {
        "subject": "Help Needed in Booking Family Suite in Rome",
        "body": "Dear Support Team, as a loyal customer I'm trying to book a family suite in Rome for my family of five. However, I can't seem to find a suitable one on your website. Can you help me find a hotel that can accommodate us comfortably? \nMany Thanks,  \nJane Smith ",
        "senderEmailAddress": "jane.smith@tttraveler.org"
    },
    {
        "subject": "Help Needed in Booking President Suite in Singapore",
        "body": "Dear Support Team, I'm trying to book a president suite in Singapore for my team of fifty. However, I can't seem to find a suitable one on your website. Can you help me find a hotel that can accommodate us comfortably? \nMany Thanks,  \nJordan Belford ",
        "senderEmailAddress": "jordan.belford@stratton-oakmont.org"
    },
    {
        "subject": "ヨーロッパ複数都市ツアーの支援が必要です",
        "body": "こんにちは、ThorToursチームの皆様、来年の夏にヨーロッパで複数の都市を巡るツアーを計画しており、飛行機やホテルの予約方法について最適な方法が分からずにいます。ローマ、パリ、ベルリン、バルセロナを含む旅程を作成するお手伝いをしていただけますか？\nよろしくお願いいたします。\nトム・デイビス\n",
        "senderEmailAddress": "tom.davis@tttraveler.org"
    }
  ]
}


### GET MAILS
# @name getMails
GET {{btpAppHostname}}/odata/v4/mail-insights/Mails
content-type: application/json
Authorization: Bearer {{token}}


### GET MAIL

@id = {{getMails.response.body.$.[3].ID}}

# @name getMail
GET {{btpAppHostname}}/odata/v4/mail-insights/getMail(id={{id}})
content-type: application/json
Authorization: Bearer {{token}}


### REGENERATE RESPONSE 

@id = {{getMails.response.body.$.[3].ID}}

# @name regenerateResponse
POST {{btpAppHostname}}/odata/v4/mail-insights/regenerateResponse
content-type: application/json
Authorization: Bearer {{token}}

{
    "id": "{{id}}",
    "rag": false,
    "additionalInformation" : "Provide additional information on the climate situation in Europe"
}


### TRANSLATE RESPONSE

@id = {{getMails.response.body.$.[3].ID}}

# @name translateResponse
POST {{btpAppHostname}}/odata/v4/mail-insights/translateResponse
content-type: application/json
Authorization: Bearer {{token}}

{
    "id": "{{id}}",
    "response": "Lieber Kunde,\ndies ist eine Beispielantwort.\n\nBeste Grüße,\nIhr ThorTours Team"
}


### SUBMIT RESPONSE

@id = {{getMails.response.body.$.[3].ID}}

# @name submitResponse
POST {{btpAppHostname}}/odata/v4/mail-insights/submitResponse
content-type: application/json
Authorization: Bearer {{token}}

{
    "id": "{{id}}",
    "response": "Vážený zákazníku,\ntoto je vzorová odpověď.\n\nS pozdravem,\nVáš John-Doe - tým ThorTours",
    "translation": "Lieber Kunde,\ndies ist eine Beispielantwort.\n\nBeste Grüße,\nIhr ThorTours Team",
    "modified": true
}