{{ if .Values.expose.enabled }}
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ include "aisaas-broker.fullname" . }}
  labels: {{- include "aisaas-broker.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.global.gateway | default "kyma-system/kyma-gateway" }}
  host: {{ printf "%s.%s" ( include "aisaas-broker.exposeHost" . ) $.Values.global.domain }}
  rules:
  - methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"]
    path: /.*
    accessStrategies:
      - handler: allow
  service:
    name: {{ include "aisaas-broker.fullname" . }}
    port: {{ .Values.port }}
{{ end }}
