apiVersion: v1
kind: Service
metadata:
  name: {{ include "aisaas-broker.fullname" . }}
  labels: {{- include "aisaas-broker.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector: {{- include "aisaas-broker.selectorLabels" . | nindent 4 }}
