global:
  imagePullSecret: {}
  image: {}
  partOf: aisaas
  component: api
  domain:
  gateway: 

port: 5000

serviceAccount:
  enabled: false # If true, own serviceAccount (<<ReleaseName>>-api) used by pod, otherwise "default" serviceAccount
  automountToken: false # If true, token of the assigned serviceAccount (default or fullname) automounted

image: {}
imagePullSecret: {}
additionalVolumes: []


ha: # High-Availability
  enabled: true
  pdb: # Pod Disruption Budget
    minAvailable: 1 

hpa: # Horizontal Pod Autoscaler
  enabled: true
  minReplicaCount: 1 # To use High-Availibility set minReplicaCount to at least 2
  maxReplicaCount: 3
  cpuTargetAverageUtilization: 80 # Either choose Target Average Utilization or Value
  cpuTargetAverageValue:

health_check:
  liveness:
    path: /healthz
  readiness:
    path: /healthz

startupTimeout: 30

resources:
  limits:
    ephemeral-storage: 
    memory: 
    cpu: 
  requests:
    ephemeral-storage: 
    cpu: 
    memory: 

expose: 
  enabled: true # If true, your workload will be exposed via Istio Ingressgateway

serviceKeys: {}

# Settings for SAP API Management integration
apim:
  # Only enable if SAP API Management instance is configured
  enabled: 
  # SAP API Management runtime host w/o "https://" or port
  host: 
  # Port of SAP API Management runtime host
  port: 
  # Path of API Proxy in SAP API Management
  path: 
  # Provide details of the API XSUAA Service Instance
  # Those details can be found in the respective Kyma Secret
  # The Secret is created for the xsuaa-apim serviceKey
  xsuaa: 
    # Provide the XSUAA tenant host without https://
    # e.g., sap-demo.authentication.us20.hana.ondemand.com
    host: 
    # Provide the xsappname of your API XSUAA Service Instance 
    # Add the prefix "sb-" to the xsappname like, sb-aisaas-api-default
    sub: 
  
