apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aisaas-api.fullname" . }}
  labels: {{- include "aisaas-api.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels: {{- include "aisaas-api.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: istio-ingressgateway
        namespaceSelector:
          matchLabels:
            name: istio-system