
### EMBED
# @name embed
POST http://localhost:4004/odata/v4/mail-insights/embed
content-type: application/json
Authorization: Basic alice:

{
    "texts": [
    "Couples waltz gracefully across the dance floor, bathed in soft, romantic lighting.",
    "A blacksmith hammers a piece of glowing metal, sparks flying in all directions.",
    "The first snow of winter blankets the landscape in a serene, white quietness.",
    "The aroma of sizzling bacon and fresh coffee fills the kitchen on a lazy morning.",
    "A scientist makes a groundbreaking discovery, unlocking the mysteries of the universe."
  ]
}

### SIMILARITY SEARCH
# @name simSearch
POST http://localhost:4004/odata/v4/mail-insights/simSearch
content-type: application/json
Authorization: Basic alice:

{
    "text": "At the wedding, the dance floor came alive as the bride and groom swayed in each other's arms.",
    "k": 2
}

### ADD MAILS
# @name addMails
POST http://localhost:4004/odata/v4/mail-insights/addMails
content-type: application/json
Authorization: Basic alice:

{
  "mails": [{
    "sender": "test.sender@example.org",
    "subject": "Test Mail",
    "body": "Dear Adi Pleyer, I am not very happy with the delivery I received from you. The motor is not reaching the desired speed and produces strange sounds. I would like to return the vehicle. Please let me know how I can give it back to you. Best regards, Kay"
  }]
}


### GET MAIL
@id = {{addMails.response.body.$.value[0].id}}

# @name getMail
GET http://localhost:4004/odata/v4/mail-insights/getMail(id={{id}})
content-type: application/json
Authorization: Basic alice:

