apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ include "aisaas-router.fullname" . }}
  labels: {{- include "aisaas-router.labels" . | nindent 4 }}
spec:
  workloadSelector: 
    labels: {{- include "aisaas-router.selectorLabels" . | nindent 6 }}
  egress:
    - hosts:
      - ./*
      - istio-system/*