apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "aisaas-router.fullname" . }}
  labels: {{- include "aisaas-router.labels" . | nindent 4 }}
spec:
  host: {{ printf "%s.%s.svc.cluster.local" ( include "aisaas-router.fullname" . )  .Release.Namespace }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: JSESSIONID
          path: /
          ttl: 0s