global:
  imagePullSecret: {}
  domain: a1b2c3.kyma.ondemand.com
  shootName: a1b2c3 

router:
  image:  
    repository: sap-demo/aisaas-router
    tag: latest

srv:
  image:
    repository: sap-demo/aisaas-srv
    tag: latest

api:
  image:
    repository: sap-demo/aisaas-api
    tag: latest

broker:
  image:
    repository: sap-demo/aisaas-broker
    tag: latest
  config: 
    serviceId: 11111111-1111-1111-1111-111111111111
    plans:
      - name: default
        description: GenAI Mail Insights default plan
        planId: 22222222-2222-2222-2222-222222222222
      - name: premium
        description: GenAI Mail Insights premium plan
        planId: 33333333-3333-3333-3333-333333333333
      - name: trial
        description: GenAI Mail Insights trial plan
        planId: 44444444-4444-4444-4444-444444444444

hana_deployer:
  image:
    repository: sap-demo/aisaas-db-com
    tag: latest

html5_apps_deployer:
  image:
    repository: sap-demo/aisaas-html5-deployer
    tag: latest

xsuaa:
  parameters:
   oauth2-configuration:
    redirect-uris:
      - https://*.a1b2c3.kyma.ondemand.com/**
      - http://*.localhost:5000/**
      - http://localhost:5000/**