global:
  imagePullSecret: {}
  image: {}
  partOf: aisaas
  component: router
  domain: 
  gateway: 

port: 5000

serviceAccount:
  enabled: true # If true, own serviceAccount (<<ReleaseName>>-router) used by pod, otherwise "default" serviceAccount
  automountToken: false # If true, token of the assigned serviceAccount (default or fullname) automounted

image: {}
imagePullSecret: {}
additionalVolumes: []

resources: 
  limits:
    ephemeral-storage: 
    memory: 
    cpu: 
  requests:
    ephemeral-storage: 
    cpu: 
    memory: 

expose:
  enabled: true

ha:
  enabled: true
  pdb:
    minAvailable: 1

hpa:
  enabled: true
  minReplicaCount: 1 
  maxReplicaCount: 3
  cpuTargetAverageUtilization: 80
  cpuTargetAverageValue:

health_check:
  liveness:
    path: /healthz
  readiness:
    path: /healthz

startupTimeout: 30