{{- if .Values.apim.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "aisaas-api.fullname" . }}-apim
  labels: {{- include "aisaas-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "aisaas-api.selectorLabels" . | nindent 6 }}
  jwtRules:
  - issuer: {{ printf "https://%s/oauth/token" .Values.apim.xsuaa.host }}
    jwksUri: {{ printf "https://%s/token_keys" .Values.apim.xsuaa.host }}
    fromHeaders:
    - name: x-jwt-assertion
{{- end }}